### ISSUE TITLE
PYROWL does not work since August 20, 2017 -SSL issue with Prowl-API

### ISSUE THREAD

**Issue by burniegeroellheimer** [babs/pyrowl#8]
Prowl changed their API in August 2017.
Prowl Support told me, that the Prowl API now requires SNI.
However, my Pyrowl-installations do not work with the new API anymore.
Is there a plan to update Pyrowl?

**Comment by babs** [comment]
I don't use pyrowl anymore but I'd be glad to accept PR for that :)

**Comment by gmorain** [comment]
Hi, 

I just submitted a pull request solving the issue (at least for me)

Gilles

**Comment by babs** [comment]
PR merged (with lots of delaydm, sorry).
